import Header from "@/components/header/Header";
import "./globals.css";
import type { Metadata } from "next";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" style={{overflow:'auto'}}>
       
      <body style={{ fontFamily: 'Prompt, sans-serif' }}>
      <link
          href="https://fonts.googleapis.com/css2?family=Prompt:wght@100;200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
        <Header></Header>
        <div className=" bg-black" style={{height:'calc(100vh - 80px)'}}> {children}</div>
      </body>
    </html>
  );
}
